const { models } = require('../server/db')
const { anonVisitor } = models

const makeAnonVisitor = (
  requestedUsername,
  firstName,
  lastName,
  eMail,
  aboutYou,
  firstCat,
  otherPets,
  city,
  state,
  budget,
  fB,
  iG,
  gender,
  ears,
  eyeColor,
  furColor,
  mif,
) => ({
  requestedUsername,
  firstName,
  lastName,
  eMail,
  aboutYou,
  firstCat,
  otherPets,
  city,
  state,
  budget,
  fB,
  iG,
  gender,
  ears,
  eyeColor,
  furColor,
  mif,
})

const anonVisitorsArray = [
  makeAnonVisitor(
    'callMeBob',
    'anon1First',
    'anon1Last',
    '432@gmail.com',
    'i am an anon visitor',
    true,
    'dogs',
    'brooklyn',
    'new york',
    'lessThan1500',
    'myFB',
    'myIG',
    'boy',
    'fold',
    'blue',
    'gold',
    'the most important thing i look for in a cat is ears',
  ),
  makeAnonVisitor(
    'callMeAlice',
    'anon2First',
    'anon2Last',
    '4221@gmail.com',
    'i am an another anon visitor',
    false,
    'no',
    'high point',
    'north Carolina',
    'lessThan1500',
    'myFB',
    'myIG',
    'boy',
    'fold',
    'blue',
    'gold',
    'the most important thing i look for in a cat is ears',
  )
]

module.exports = anonVisitorsArray
