const makeKitten = (
  name, ears, furColor, eyeColor, dob, status, description, image
) => ({
  name,
  ears,
  furColor,
  eyeColor,
  status,
  dob,
  description,
  image,
})

const kittensArray = [
  {
    name: '',
    gender: '',
    ears: '',
    furColor: '',
    eyeColor: '',
    dob: '',
    mother: '',
    father: '',
    status: '',
    description: '',
    breed:'',
    mainImageSrcValue: '',
  },
  {
    name: '',
    gender: '',
    ears: '',
    furColor: '',
    eyeColor: '',
    dob: '',
    mother: '',
    father: '',
    status: '',
    description: '',
    breed:'',
    mainImageSrcValue: '',
  },
  {
    name: '',
    gender: '',
    ears: '',
    furColor: '',
    eyeColor: '',
    dob: '',
    mother: '',
    father: '',
    status: '',
    description: '',
    breed:'',
    mainImageSrcValue: '',
  },
  {
    name: '',
    gender: '',
    ears: '',
    furColor: '',
    eyeColor: '',
    dob: '',
    mother: '',
    father: '',
    status: '',
    description: '',
    breed:'',
    mainImageSrcValue: '',
  },
  {
    name: '',
    gender: '',
    ears: '',
    furColor: '',
    eyeColor: '',
    dob: '',
    mother: '',
    father: '',
    status: '',
    description: '',
    breed:'',
    mainImageSrcValue: '',
  },
  {
    name: '',
    gender: '',
    ears: '',
    furColor: '',
    eyeColor: '',
    dob: '',
    mother: '',
    father: '',
    status: '',
    description: '',
    breed:'',
    mainImageSrcValue: '',
  },
  {
    name: '',
    gender: '',
    ears: '',
    furColor: '',
    eyeColor: '',
    dob: '',
    mother: '',
    father: '',
    status: '',
    description: '',
    breed:'',
    mainImageSrcValue: '',
  },
]


module.exports = kittensArray
