const kittensArray = [
  //  Felisiya
  {
    name: 'Finley',
    breed:'Scottish Straight Shorthair',
    gender: 'Boy',
    ears: 'Straight',
    furColor: 'Silver Chinchilla Point',
    eyeColor: 'Blue',
    dob: 'March 16th, 2022',
    mother: 'Felisiya',
    father: 'Artemis',
    price: 1900,
    location: 'Bergenfield, New Jersey',
    description: '',
    mainImageSrcValue: '/catPictures/kittenFelisiyaFinley.jpg',
    status: "Sold",
    },
  {
    name: 'Einstein',
    gender: 'Boy',
    breed: 'Scottish Fold',
    eyeColor: 'Green',
    mother: 'Felisiya',
    price: 2100,
    mainImageSrcValue: '/catPictures/kittenFelisiyaEinstein.jpg',
    status: "Sold",
  },
  {
    name: 'Freya',
    mother: 'Felisiya',
    price: 1700,
    mainImageSrcValue: '/catPictures/kittenFelisiyaFreya.jpg',
    status: "Sold",
  },
  {
    name: 'Frosty',
    mother: 'Felisiya',
    price: 1700,
    mainImageSrcValue: '/catPictures/kittenFelisiyaFrosty.jpg',
    status: "Sold",
  },
  {
    name: 'Sunny',
    mother: 'Felisiya',
    price: 2300,
    mainImageSrcValue: '/catPictures/kittenFelisiyaSunny.jpg',
    status: "Sold",
  },
  // Danissima
  {
    name: 'Dew',
    breed:'Scottish Fold Shorthair',
    gender: 'Girl',
    ears: 'Fold',
    furColor: 'Silver Shaded Chinchilla',
    eyeColor: 'Green',
    dob: 'April 27th, 2022',
    mother: 'Danissima',
    father: 'Artemis',
    price: 2300,
    location: 'Bergenfield, New Jersey',
    description: '',
    mainImageSrcValue: '/catPictures/kittenDanissimaDew.jpg',
    status: "Sold",
  },
  {
    name: 'Daiquiri',
    breed:'Scottish Straight Shorthair',
    gender: 'Girl',
    ears: 'Straight',
    furColor: 'Silver Shaded Chinchilla',
    eyeColor: 'Green',
    dob: 'April 27th, 2022',
    mother: 'Danissima',
    father: 'Artemis',
    price: 1700,
    location: 'Bergenfield, New Jersey',
    description: '',
    mainImageSrcValue: '/catPictures/kittenDanissimaDaiquiri.jpg',
  },
  {
    name: 'Elsa',
    breed:'Scottish Straight Shorthair',
    gender: 'Girl',
    ears: 'Straight',
    furColor: 'Silver Shaded Chinchilla',
    eyeColor: 'Green',
    dob: 'April 27th, 2022',
    mother: 'Danissima',
    father: 'Artemis',
    price: 1700,
    location: 'Bergenfield, New Jersey',
    description: '',
    mainImageSrcValue: '/catPictures/kittenDanissimaElsa.jpg',
    status: 'Sold',
    },
  {
    name: 'Dumpling',
    breed:'Scottish Fold Shorthair',
    gender: 'Boy',
    ears: 'Fold',
    furColor: 'Silver Shaded Chinchilla',
    eyeColor: 'Green',
    dob: 'April 27th, 2022',
    mother: 'Danissima',
    father: 'Artemis',
    price: 2300,
    location: 'Bergenfield, New Jersey',
    description: '',
    mainImageSrcValue: '/catPictures/kittenDanissimaDumpling.jpg',
    status: 'Sold',
  },
  {
    name: 'Dolce Gabbana',
    breed: 'Scottish Straight Shorthair',
    gender: 'Boy',
    ears: 'Straight',
    furColor: 'White',
    eyeColor: 'Odd',
    dob: 'April 27th, 2022',
    mother: 'Danissima',
    father: 'Artemis',
    price: 2500,
    location: 'Bergenfield, New Jersey',
    description: '',
    mainImageSrcValue: '/catPictures/kittenDanissimaDG.jpg',
  },
    // BumbleBee
  {
    name: 'Fudge',
    breed: 'Scottish Straight Shorthair',
    gender: 'Boy',
    ears: 'Straight',
    furColor: 'Black Marble Tabby',
    eyeColor: 'Yellow',
    dob: 'March 30th, 2022',
    mother: 'BumbleBee',
    father: 'Pompano',
    price: 1500,
    location: 'Fort Lauderdale, Florida',
    description: '',
    mainImageSrcValue: '/catPictures/kittenBumblebeeFudge.jpg',
    status: 'Sold',

  },
  // Lucia
  {
    name: 'Olaf',
    breed:'Scottish Straight Shorthair',
    gender: 'Boy',
    ears: 'Straight',
    furColor: 'Blue Bicolor Tabby',
    eyeColor: 'Green',
    dob: 'June 8th, 2022',
    mother: 'Lucia',
    father: 'Artemis',
    price: 1600,
    location: 'High Point, North Carolina',
    description: '',
    mainImageSrcValue: '/catPictures/kittenLuciaOlaf.jpg',
  },
  {
    name: 'Koda',
    breed:'Scottish Straight Shorthair',
    gender: 'Boy',
    ears: 'Straight',
    furColor: 'Brown Ticked Bicolor',
    eyeColor: 'Green',
    dob: 'June 8th, 2022',
    mother: 'Lucia',
    father: 'Artemis',
    price: 1600,
    location: 'High Point, North Carolina',
    description: '',
    mainImageSrcValue: '/catPictures/kittenLuciaKoda.jpg',
  },
  {
    name: 'Baloo',
    breed:'Scottish Straight Shorthair',
    gender: 'Boy',
    ears: 'Straight',
    furColor: 'Brown Ticked Bicolor',
    eyeColor: 'Green',
    dob: 'June 8th, 2022',
    mother: 'Lucia',
    father: 'Artemis',
    price: 1600,
    location: 'High Point, North Carolina',
    description: '',
    mainImageSrcValue: '/catPictures/kittenLuciaBaloo.jpg',
  },
  {
    name: 'Tiana',
    breed:'Scottish Straight Shorthair',
    gender: 'Girl',
    ears: 'Straight',
    furColor: 'Blue Ticked Bicolor',
    eyeColor: 'Green',
    dob: 'June 8th, 2022',
    mother: 'Lucia',
    father: 'Artemis',
    price: 1600,
    location: 'High Point, North Carolina',
    description: '',
    mainImageSrcValue: '/catPictures/kittenLuciaTiana.jpg',
  },
  {
    name: 'Jasmine',
    breed:'Scottish Straight Shorthair',
    gender: 'Girl',
    ears: 'Straight',
    furColor: 'Brown Ticked Bicolor',
    eyeColor: 'Green',
    dob: 'June 8th, 2022',
    mother: 'Lucia',
    father: 'Artemis',
    price: 1600,
    location: 'High Point, North Carolina',
    description: '',
    mainImageSrcValue: '/catPictures/kittenLuciaJasmine.jpg',
  },
  {
    name: 'Merida',
    breed:'Scottish Straight Shorthair',
    gender: 'Girl',
    ears: 'Straight',
    furColor: 'Black Tabby',
    eyeColor: 'Green',
    dob: 'June 8th, 2022',
    mother: 'Lucia',
    father: 'Artemis',
    price: 1600,
    location: 'High Point, North Carolina',
    description: '',
    mainImageSrcValue: '/catPictures/kittenLuciaMerida.jpg',
  },
    // Iris
  {
    name: 'Bentley',
    breed:'Scottish Straight Shorthair',
    gender: 'Boy',
    ears: 'Straight',
    furColor: 'Blue Colorpoint',
    eyeColor: 'Blue',
    dob: 'June 19th, 2022',
    mother: 'Iris',
    father: 'Brooklyn',
    price: 2500,
    location: 'Hight Point, North Carolina',
    description: '',
    mainImageSrcValue: '/catPictures/kittenIrisBentley.jpg',
  },
  {
    name: 'Nola',
    mother: 'Iris',
    price: 1800,
    mainImageSrcValue: '/catPictures/kittenIrisNola.jpg',
    status: "Sold",
  },
  {
    name: 'Pearl',
    mother: 'Iris',
    price: 2300,
    mainImageSrcValue: '/catPictures/kittenIrisPearl.jpg',
    status: "Sold",
  },
  {
    name: 'Ivy',
    mother: 'Iris',
    price: 2300,
    mainImageSrcValue: '/catPictures/kittenIrisIvy.jpg',
    status: "Sold",
  },

  //  7/25 litter
  {
    name: 'Honey',
    breed: 'Scottish Straight Shorthair',
    gender: 'Girl',
    ears: 'Straight',
    furColor: 'Black Golden Shaded',
    eyeColor: 'Green',
    status: 'Available',
    dob: 'July 25th, 2022',
    mother: 'Felisiya',
    father: 'Artemis',
    price: 1900,
    description: '',
    location: 'Bergenfield, New Jersey',
    mainImageSrcValue: '/catPictures/7-25litter/kittenFelisiyaHoneyReserved.jpg',
    status: "Reserved",
  },
  {
    name: 'Grant',
    breed: 'Scottish Straight Shorthair',
    gender: 'Boy',
    ears: 'Straight',
    furColor: 'Black Golden Shell',
    eyeColor: 'Green',
    status: 'Available',
    dob: 'July 25th, 2022',
    mother: 'Felisiya',
    father: 'Artemis',
    price: 2300,
    description: '',
    location: 'Bergenfield, New Jersey',
    mainImageSrcValue: '/catPictures/7-25litter/kittenFelisiyaGrantReserved.jpg',
    status: 'Reserved',
  },
  {
    name: 'Goji',
    breed: 'Scottish Fold Shorthair',
    gender: 'Boy',
    ears: 'Fold',
    furColor: 'Black Silver Shaded',
    eyeColor: 'Green',
    status: 'Available',
    dob: 'July 25th, 2022',
    mother: 'Felisiya',
    father: 'Artemis',
    price: 2300,
    description: '',
    location: 'Bergenfield, New Jersey',
    mainImageSrcValue: '/catPictures/7-25litter/kittenFelisiyaGoji.jpg',
  },
  {
    name: 'TBD1',
    breed: 'Scottish Fold Shorthair',
    gender: 'Boy',
    ears: 'Fold',
    furColor: 'Silver Chinchilla Point',
    eyeColor: 'Blue',
    status: 'Available',
    dob: 'July 25th, 2022',
    mother: 'Felisiya',
    father: 'Artemis',
    price: 2300,
    description: '',
    location: 'Bergenfield, New Jersey',
    mainImageSrcValue: '/catPictures/7-25litter/kittenFelisiyaTBD1.jpg',
  },
  {
    name: 'TBD2',
    breed: 'Scottish Straight Shorthair',
    gender: 'Boy',
    ears: 'Straight',
    furColor: 'Silver Chinchilla Point',
    eyeColor: 'Blue',
    status: 'Available',
    dob: 'July 25th, 2022',
    mother: 'Felisiya',
    father: 'Artemis',
    price: 1900,
    description: '',
    location: 'Bergenfield, New Jersey',
    mainImageSrcValue: '/catPictures/7-25litter/kittenFelisiyaTBD2.jpg',
  },
  {
    name: 'TBD3',
    breed: 'Scottish Straight Shorthair',
    gender: 'Boy',
    ears: 'Straight',
    furColor: 'Silver Chinchilla Point',
    eyeColor: 'Blue',
    status: 'Available',
    dob: 'July 25th, 2022',
    mother: 'Felisiya',
    father: 'Artemis',
    price: 1900,
    description: '',
    location: 'Bergenfield, New Jersey',
    mainImageSrcValue: '/catPictures/7-25litter/kittenFelisiyaTBD3.jpg',
  },
]

module.exports = kittensArray
